{{- if .Values.apiGateway.ingress.enabled }}
{{- if not (eq .Values.apiGateway.ingress.className "nginx") }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "mall-demo.labels" (dict "name" "ingress" "Chart" .Chart "Release" .Release) | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
spec:
  ingressClassName: {{ .Values.apiGateway.ingress.className | default "nginx" }}
  rules:
    - host: {{ .Values.apiGateway.ingress.host }}
      http:
        paths:
          - path: /api(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: api-gateway
                port:
                  number: 8080
          - path: /health
            pathType: Prefix
            backend:
              service:
                name: api-gateway
                port:
                  number: 8080
{{- end }}
{{- end }}
