{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "mall-demo.labels" (dict "name" .Values.serviceAccount.name "Chart" .Chart "Release" .Release) | nindent 4 }}
{{- end }}
